-- Generated by drizzle-kit. Uses IF NOT EXISTS / IF EXISTS guards because
-- 0002_freshness_overhaul.sql already applied these changes to the production Neon DB.
-- Safe to run on any environment regardless of prior state.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_seen_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "personal_profiles" DROP COLUMN IF EXISTS "freshness_reminders_enabled";--> statement-breakpoint
ALTER TABLE "teams" DROP COLUMN IF EXISTS "freshness_reminders_enabled";
